language: python

python:
  - 2.7

env:
  - DJANGO=https://github.com/django/django/tarball/master
  - DJANGO=Django==1.6.5

install:
  - pip install flake8 coverage coveralls
  - pip install -e .
  - pip install $DJANGO

script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark agora
  - coverage run setup.py test
  - coverage report

after_success: coveralls
